services:
  - type: web
    plan: free
    name: project_django
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn project_django.asgi:application -k uvicorn.workers.UvicornWorker"
